// @keepTs
// @ts-nocheck
export declare class LogUtil {
    private static TAG;
    private static dtxTagPrefix;
    private static USE_SCP_LOG;
    static v(t13: string, u13: string): void;
    static d(r13: string, s13: string): void;
    static i(p13: string, q13: string): void;
    static w(n13: string, o13: string): void;
    static e(l13: string, m13: string): void;
    static f(j13: string, k13: string): void;
    static napMs(h13: number): Promise<void>;
}
