// @keepTs
// @ts-nocheck
/**
 * Use these variables when you tailor your ArkTS code. They must be of the const type.
 */
export declare const HAR_VERSION = "1.0.30";
export declare const BUILD_MODE_NAME = "release";
export declare const DEBUG = false;
export declare const TARGET_NAME = "default";
export declare const USE_ANT_NETWORK_LIB = false;
export declare const NOT_EMBED_EDGE = true;
export declare const HAR_NAME = "blueshieldsdk";
/**
 * BuildProfile Class is used only for compatibility purposes.
 */
export default class BuildProfile {
    static readonly HAR_VERSION = "1.0.30";
    static readonly BUILD_MODE_NAME = "release";
    static readonly DEBUG = false;
    static readonly TARGET_NAME = "default";
    static readonly USE_ANT_NETWORK_LIB = false;
    static readonly NOT_EMBED_EDGE = true;
    static readonly HAR_NAME = "blueshieldsdk";
}
