export declare enum Biz_Type {
    common = "common",
    tongji = "tongji",
    push = "push",
    apm = "apm",
    verify = "verify",
    link = "link",
    share = "share",
    zid = "zid",
    asm = "asm",
    b1 = "b1",
    b2 = "b2",
    b3 = "b3",
    b4 = "b4",
    b5 = "b5",
    b6 = "b6",
    b7 = "b7",
    b8 = "b8",
    b9 = "b9"
}
